# Generated by Django 5.2.1 on 2025-05-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
    ]
